Repository Leshens/LetsEatWeb, pull requests merged in 2023-12, with the labels that each got.

#32 Leshens/SecurityBreach
  .env
  .github/workflows/node.js.yml
  .gitignore
  src/firebase.js
Labels: bug

#31 Create dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: dependencies

#33 Delete .env
  .env
Labels: bug

#39 added protected to pages
  package-lock.json
  src/App.js
  src/components/Protected.jsx
Labels: enhancement

#45 obsługa błędów firebase
  src/pages/Login.js
  src/pages/SignUp.js
  src/schemas/index.js
  src/schemas/loginSchema.js
  tailwind.config.js
Labels: enhancement
